
# Cluster
NUM_OF_NODES = 3
NODE_CAPACITY = 1
NODE_MEMORY = 1
AVERAGE_CLUSTER_MEMORY_DEMAND = 0.8
POD_MEMORY_EXPECTATION = 0.2
POD_MEMORY_VARIANCE = 0.1
POD_MIN_MEMORY = 0.05
SPAWN_TIME_INTERVAL_SECS = 0.0001
MIN_TIME_POD = 0.001
MAX_TIME_POD = 0.01
AVERAGE_POD_LIFETIME = (MAX_TIME_POD + MIN_TIME_POD) / 2
MAX_NUM_OF_PODS = (((NUM_OF_NODES * NODE_CAPACITY) / POD_MEMORY_EXPECTATION) // AVERAGE_POD_LIFETIME) \
                  * AVERAGE_CLUSTER_MEMORY_DEMAND * 1.1
RUN_TIME_SECONDS = 60 * 6

# Learning
NUM_OF_BUCKETS = 10
PERCENTAGE = 100 / NUM_OF_BUCKETS
PODS_LOOKAHEAD = 1
SECONDS_PER_EPOCH = RUN_TIME_SECONDS
REWARD_FACTOR = 100

# Agent
ALPHA = 0.3  # 0.7
GAMMA = 0.3
EPSILON = 0.15

# Logging
UTILITY_LOG_INTERVAL_SECS = RUN_TIME_SECONDS / 10  # 0.75
